version: "3"

services:
  server:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
  db:
    image: mariadb
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=car
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
    # expose:
    #   - 3306